


POST http://account-service-xan80-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/accounts/active-record
Content-Type: application/json

{
  "accountNumber":3, "customerNumber":5, "customerName":"Customer5", "balance":123321.122
}

###
GET http://account-service-xan80-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/accounts/active-record
Accept: application/json

###
GET http://account-service-xan80-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/accounts/repository
Accept: application/json

###

GET http://account-service-xan80-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/accounts/repo/
Accept: application/json

###
GET http://account-service-xan80-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/resilience/call-with-timeout

###

GET {{uri}}/accounts/repository/
Accept: application/json

### This call will lead to overdrawn account

POST {{uri}}/accounts/repository/123456789/transaction
Content-Type: application/json

600

###

GET http://localhost:8082/accounts/repository/123456789/balance
Accept: application/json

### Health checks. Introduced by quarkus-smallrye-health dependency

GET http://localhost:8082/q/health

Accept: application/json

### Health checks. Introduced by quarkus-smallrye-health dependency

GET http://localhost:8082/q/health/live

Accept: application/json

### Health checks. Introduced by quarkus-smallrye-health dependency

GET http://localhost:8082/q/health/ready

Accept: application/json

### Bulkhead trigger, call this multiple times within the sleep to trigger the bulkhead fallback

GET http://localhost:8082/resilience/do-delivery-bulkhead

### Overdrawn trigger

POST http://localhost:8082/accounts/active-record/withdraw/123456789
Content-Type: application/json

1000





