# Use postgres/example user/password credentials
version: '3.1'
name: my-compose
services:
  db:
    image: postgres
    restart: no
    container_name: db #this is used for external access within the network
    ports:
      - 5432:5432
    volumes:
      - /c/temp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: quarkus_banking
      POSTGRES_PASSWORD: quarkus_banking
      POSTGRES_DB: quarkus_banking
    networks:
      - quarkus-bank-network
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '29092:29092'
    volumes:
      - /c/temp/kafka-vol:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_ENABLE_KRAFT=true #default
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - ALLOW_PLAINTEXT_LISTENER=yes #default
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL_SAME_HOST://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_GROUP_MIN_SESSION_TIMEOUT_MS=250 #allows fast reconnection after quarkus:dev restart
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER #used by Kraft not to be included in the advertised listeners
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - BITNAMI_DEBUG=true
    networks:
      - quarkus-bank-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080" # http://localhost:8090 to reach the Kafka gui
    #restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - quarkus-bank-network

  account-service:
    image: apedano/quarkus-account-service:latest
    container_name: account-service #this is used for external access within the network
    ports:
      - "8082:8082" # http://localhost:8082
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/quarkus_banking
    depends_on:
      - kafka
      - db
    networks:
      - quarkus-bank-network
  transaction-service:
    image: apedano/quarkus-transaction-service:latest
    container_name: transaction-service #this is used for external access within the network
    ports:
      - "8088:8088" # http://localhost:8088
    environment:
      - QUARKUS_HTTP_PORT=8088
      - quarkus.rest-client.account-service.url=http://account-service:8082
    depends_on:
      - kafka
      - account-service
    networks:
      - quarkus-bank-network
  overdraft-service:
    image: apedano/quarkus-overdraft-service:latest
    container_name: overdraft-service #this is used for external access within the network
    ports:
      - "8189:8189"
    environment:
      - QUARKUS_HTTP_PORT=8189
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - account-service
    networks:
      - quarkus-bank-network
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - quarkus-bank-network
networks:
  quarkus-bank-network:
    driver: bridge